config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home', as: 'home'
  resources :users
  resources :teams
  resources :games
  resources :matches
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :score, presence: true
  validates_inclusion_of :score, :in => 0..10
  belongs_to :match
  belongs_to :team
  
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :games, dependent: :destroy
  has_many :teams, :through => :games
  
  #Determine the winner of the match
  def winner
    #Get both team of the match
    teamA          = self.teams.distinct.first
    teamB          = self.teams.distinct.second
    #Setup win counting for each team
    teamA_wincount = 0
    teamB_wincount = 0
    #Get Game result for the match Each team will have score for each game
    teamA_rs       = Game.where(team_id: teamA.id,match_id: self.id).map{|x| x.score}
    teamB_rs       = Game.where(team_id: teamB.id,match_id: self.id).map{|x| x.score}
    i              = 0
    games_count    = self.games.count/2
    #Looping through result, compare result from both side 
    games_count.times do
      if teamA_rs[i] > teamB_rs[i]
        teamA_wincount +=1
      else
        teamB_wincount +=1
      end
      i+=1
    end
    #Return result base on wincount
    teamA_wincount > teamB_wincount ? teamA : teamB
  end
  
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true,uniqueness: true
  has_many :users
  has_many :games, dependent: :destroy
  has_many :matchs, :through => :games
  
  validate :validate_max_users
  
  def winrate
    #Initialize matchs for current team
    matchs       = self.matchs.distinct
    total_matchs = self.matchs.distinct.count
    win_match    = 0
    
    #Iterate through all matchs, increase win_match if winner is "self"
    matchs.each do  |match|
      win_match += 1 if match.winner == self
    end
    #Rule out zero divider exception, convert result to float rounded to 3
    total_matchs == 0 ? 0.0 : (win_match.to_f/total_matchs).round(3)
  end
  
  #Used to return a ranked list base on winrate
  def self.ranked_list
    ranked_list = []
    #Iterate Over teams, create an array of hashes contain winrate
    Team.all.each do |team|
      team_result = {:team=>nil, :wins=> nil,
      :losses => nil,:total_match=>nil,:winrate=>nil}
      
      total_match = team.matchs.distinct.count
      wins        = (total_match * team.winrate).to_i
      losses      = total_match - wins
      team_result.store(:team, team)
      team_result.store(:total_match,total_match)
      team_result.store(:wins,wins)
      team_result.store(:losses,losses)
      team_result.store(:winrate,team.winrate)
      ranked_list << team_result
    end
    #Descending sorting
    ranked_list.sort_by {|k| k[:winrate] }.reverse
  end
  
  
  
  private
    #Maximum memeber is two
    def validate_max_users
     if self.users.size > 2
      errors[:base] << "Team can only has maximum of two users"
     end
    end
  
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name,:last_name, presence: true
  
  
  def full_name
    self.first_name + " " + self.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  
  end
  
  def show
  
  end
  
  def update

  end
  
  def destroy
  
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches     = Match.all
    @match       = Match.new
    @score_range = *(0..10)
  end
  
  def create
    @match = Match.new
    #This is a technical debt
    #If both team id are the same >> not save the match
    unless teamA_params[:id] == teamB_params[:id]
      teamA_params[:scores].each do |k, v|
        Game.create(score: v,team: Team.find(teamA_params[:id]), match: @match)
      end
      teamB_params[:scores].each do |k, v|
        Game.create(score: v,team: Team.find(teamB_params[:id]), match: @match)
      end
      
      if @match.save
        redirect_back(fallback_location: matches_path)
      else
        
      end
    else
      flash[:danger] = "Same Team cannot fight each other!"
      redirect_back(fallback_location: matches_path)
    end
  end
  
  def show
  
  end
  
  def update

  end
  
  def destroy
    Match.find(params[:id]).destroy
    flash.now[:success] = "Match Deleted!"
    redirect_back(fallback_location: matches_path)
  end
  
  private 
    def teamA_params
      params.require(:teamAgames).permit(:id, { scores: [:game1, :game2, :game3]})
    end
    
    def teamB_params
      params.require(:teamBgames).permit(:id, { scores: [:game1, :game2, :game3]})
    end
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @ranked_list = Team.ranked_list
    
    
    render 'home'
  end
  
  
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all.order('created_at desc')
  end
  
  def create
    @team = Team.new(team_params)
    if @team.save
      flash[:success] = "Team Added!"
      redirect_to teams_path
    else
      render 'new'
    end
  end
  
  def new
    @team = Team.new
  end
  
  
  def show
  
  end
  
  def edit
    @team = Team.find(params[:id])
  end
  
  def update
    @team = Team.find(params[:id])
    
    if @team.update_attributes(team_params)
      flash[:success] = "Team Updated!"
      redirect_to teams_path
    else
      render 'new'
    end
  end
  
  def destroy
    Team.find(params[:id]).destroy
    flash.now[:success] = "Team Deleted!"
    redirect_back(fallback_location: teams_path)
  end
  
  private
  def team_params
      params.require(:team).permit(:name, user_ids: [])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
    
  def index
    @users = User.all.order('created_at desc')
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user =  User.new(user_params)
    if @user.save
      flash[:success] = "User Added!"
      redirect_to users_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def show
    
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "User updated!"
      redirect_to users_path
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted!"
    redirect_back(fallback_location: users_path)
  end
  
  private
  def user_params
      params.require(:user).permit(:first_name, :last_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-dark bg-dark fixed-bottom">
  
  
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">FoosBalls</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
         <%=link_to "Home",home_path,class: "nav-link"%>
      
      </li>
      <li class="nav-item active">
        <%=link_to "Users",users_path,class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%=link_to "Teams",teams_path,class: "nav-link"%>
      </li>
      <li class="nav-item active">
        <%=link_to "Matches",matches_path,class: "nav-link"%>
      </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FantasyFooballs</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class = "container">
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><h4><%= value %></h4></div>
    <% end %>  
    </div>
    <div class ="container">
    <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/matches/index.html.erb
<div class="container">
  <h1>Matches Management</h1>
  <hr>
  <h4>Add a New Match</h4>
  <div class="jumbotron">
    <div id="match-form">
      <!--Create Match form -->
      <%= form_for(@match) do |f| %>  
        <h5>What is the result of each game?</h5>
        <hr>
        <div class ="row">
          <div class="col">
            <h5>Blue Team</h5>
              <%=select(:teamAgames,:id,options_from_collection_for_select(Team.all, :id, :name))%>
              <!--<= select(:teamAgames,:id,options_for_select(Team.all.map{|x| x.name}))%>-->
              <hr>
              <%= fields_for "teamAgames[scores]" do |score| %>
                <p>Game 1 Score <%= score.select :game1, @score_range%></p>
                <p>Game 2 Score <%= score.select :game2, @score_range%></p>
                <p>Game 3 Score <%= score.select :game3, @score_range%></p>
              <%end%>
          </div>
          <div class="col">
             <h5>Red Team</h5>
               <%=select(:teamBgames,:id,options_from_collection_for_select(Team.all, :id, :name))%>
              <!--<= select(:teamBgames,:id,options_for_select(Team.all.map{|x| x.name}))%>-->
              <hr>
              <%= fields_for "teamBgames[scores]" do |score| %>
                <p><%= score.select :game1, @score_range%></p>
                <p><%= score.select :game2, @score_range%></p>
                <p><%= score.select :game3, @score_range%></p>
              <%end%>
          </div>
        </div>
        
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
    
    <hr>
    <!--Match list-->
    <div id="matches-list">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Blue Team</th>
            <th scope="col">Red Team</th>
            <th scope="col">Winner</th>
          </tr>
        </thead>
        <tbody>
          <%@matches.each.with_index do |match,index|%>
          <tr>
            <th scope="row"><%=index%></th>
            <td><%=match.teams.distinct.first.name if match.teams.present?%></td>
            <td><%=match.teams.distinct.second.name if match.teams.present?%></td>
            <td><%=match.winner.name if match.teams.present? %></td>
            <td><button type="button" class="btn btn-info">Edit</button>
            <%= link_to "Delete", match, method: :delete, data: { confirm: "Delete this Match?" },class: "btn btn-danger" %>
            </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="container">

  <hr>
  <div class="jumbotron">
    <h1 class="display-4">SEASON OVERVIEW</h1>
    <p class="lead">An Overview of the current season</p>
    <hr>
    <h5>Total Player <span class="badge badge-pill badge-info"><%=User.count%></span></h5>
    <h5>Total Teams <span class="badge badge-pill badge-info"><%=Team.count%></span></h5>
    <h5>Total Matchs <span class="badge badge-pill badge-info"><%=Match.count%></span></h5>
    <hr>
    <%= link_to "All User", users_path,class: "btn btn-info btn-lg" %>
    <%= link_to "All Team", teams_path,class: "btn btn-info btn-lg" %>
    <%= link_to "All Matches", matches_path,class: "btn btn-info btn-lg" %>
  </div>
  <div class="jumbotron">
    <h1 class="display-4">TEAM RANKING</h1>
    <p class="lead">This will be updated when new match records are added...</p>
    <hr>
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Rank</th>
          <th scope="col">Team Name</th>
          <th scope="col">Total Match</th>
          <th scope="col">Wins</th>
          <th scope="col">Losses</th>
          <th scope="col">Winrate</th>
        </tr>
      </thead>
      <tbody>
        <%@ranked_list.each.with_index do |t,index|%>
          <tr>
            <th scope="row"><h4><span class="badge badge-pill badge-info"><%=index+=1%></span></h4></th>
            <td><h5><%=t[:team][:name] %></h5></td>
            <td><h6><%=t[:total_match] %></h6></td>
            <td><h6><%=t[:wins] %></h6></td>
            <td><h6><%=t[:losses] %></h6></td>
            <td><h5><span class="badge badge-pill badge-warning"><%=number_to_percentage(t[:winrate] * 100, precision: 0) %></span></h5></td>
          </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  
  <h3></h3>
  
  <h3></h3>

</div>

app/views/users/edit.html.erb
<h1>Edit User <%=@user.full_name%></h1>
<div class="jumbotron">
    <div id="user-form">
      <%= form_for(@user)  do |f| %>
        <%= render 'shared/errors_messages', object: f.object %>
        <div class="row">
          <div class="col">
            <%= f.text_field :first_name, class: 'form-control',placeholder:"First name" %>
          </div>
          <div class="col">
             <%= f.text_field :last_name, class: 'form-control',placeholder:"Last name" %>
          </div>
        </div>
        <hr>
        <%= f.submit "Save Changes", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <h1>Users Management</h1>
  <hr>
  <h4>All User</h4>
  <div class="jumbotron">
    <%= link_to "Add New User", new_user_path,class: "btn btn-success" %>
    <hr>
    <!--User list-->
    <div id="users-list">
      <table class="table table-dark">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Full Name</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
          <%@users.each.with_index do |user,index|%>
          <tr>
            <th scope="row"><%=index+=1%></th>
            <td><%=user.first_name%></td>
            <td><%=user.last_name%></td>
            <td><%=user.full_name%></td>
            <td><%= link_to "Edit", edit_user_path(user),class: "btn btn-info" %>
            <%= link_to "Delete", user, method: :delete, data: { confirm: "Delete User #{user.first_name}" },class: "btn btn-danger" %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Create new User</h1>
<hr>
<div class="jumbotron">
    <div id="user-form">
      <%= form_for(@user)  do |f| %>
        <%= render 'shared/errors_messages', object: f.object %>
        <div class="row">
          <div class="col">
            <%= f.text_field :first_name, class: 'form-control',placeholder:"First name" %>
          </div>
          <div class="col">
             <%= f.text_field :last_name, class: 'form-control',placeholder:"Last name" %>
          </div>
        </div>
        <hr>
        <%= f.submit "Add", class: "btn btn-primary" %>
      <% end %>
    </div>
</div>